### ISSUE TITLE
could give us a pre-trained model for test ??

### ISSUE THREAD

**Issue by zuixiaosanlang** [junshengzhou/CAP-UDF#2]

**Comment by junshengzhou** [comment]
Hi,
Thanks for your interest. I provide a pretrained model for _'gargoyle'_ in SRB dataset [here](https://drive.google.com/drive/folders/1sPxNxAgJBfrA8ESPZP-s_8NyhO4Fvhc3?usp=sharing). However, it will take only about 30 mins for the convergence of CAP. So it will be easy to train the model yourself.
