### ISSUE TITLE
所提方法泛化能力好吗？对每一个新场景，是否需要重新训练

### ISSUE THREAD

**Issue by zuixiaosanlang** [junshengzhou/CAP-UDF#4]
看代码，模型仅拟合一个场景数据

**Comment by junshengzhou** [comment]
Hi,
Thanks for your interest. In fact, CAP is designed to reconstruct surfaces from the raw point cloud, where no additional training data is provided (like unsupervised learning). We aim to optimize a field, not learning the field in a data-driven way, so we do not focus on the generalization. 
If you are still confused, you can refer to Neural-Pull and SAL, which also optimize the single field like ours.
