### ISSUE TITLE
Speed of training

### ISSUE THREAD

**Issue by Sylva-Lin** [junshengzhou/CAP-UDF#5]
Hi, thanks for your great work! I wanted to know how to increase the speed of training, I change batch_size did not work，and GPU memory is not change.

**Comment by junshengzhou** [comment]
Hi,
Thanks for your interest! It is an interesting future work to accelerate the training of CAP. For now, CAP requires about 20k-40k iterations for convergence, but you can change it to 10k or even fewer for some simple shapes.
