### ISSUE TITLE
ShapeNetCars

### ISSUE THREAD

**Issue by Feynben** [junshengzhou/CAP-UDF#6]
Hi, thanks for your excellent work. May I ask when the full set data of ShapeNetCars will be uploaded?

**Comment by junshengzhou** [comment]
Hi,

Thanks for your interest! We have been busy with other projects recently, but we will find some time to upload the data. Actually, we have provided the detailed instructions to train CAP with different kind of point clouds. It will be easy to download the raw ShapeNetCore v1 dataset from [here](https://shapenet.org/) and sample points uniformly to train CAP. Maybe you can have a try.

best,

**Comment by Feynben** [comment]
Many thanks! I will process the dataset by myself following your instructions.
