### ISSUE TITLE
Training with custom data

### ISSUE THREAD

**Issue by minar09** [junshengzhou/CAP-UDF#7]
Hi, thanks for the awesome work. Is there a way to generate training data from existing 3D meshes? Thank you.

**Comment by junshengzhou** [comment]
Hi,

Thanks for your interest. We have provided the detailed instructions to train CAP with your own data as described in **'Use Your Own Data'** of README.  To start from meshes, you can easily sample a point cloud from a mesh using Trimesh, and then put the point cloud to the data folder to training CAP.

Best,

**Comment by minar09** [comment]
Hi @junshengzhou thank you for the info. Appreciate it.
