### ISSUE TITLE
Bug Report: Caused by New Version of Point-Cloud-Utils

### ISSUE THREAD

**Issue by Parallelopiped** [junshengzhou/CAP-UDF#9]
At the time of the current issue submission, the point-cloud-utils version installed by default using pip is `0.30.0`. When running `run.py` and iterating until `step1_maxiter`, the following error occurs:：
```
Traceback (most recent call last):
  File "run.py", line 272, in <module>
    runner.train()
  File "run.py", line 150, in train
    idx = pcu.downsample_point_cloud_poisson_disk(gen_pointclouds, num_samples=int(self.conf.get_float('train.extra_points_rate')*point_gt.shape[0]))
TypeError: downsample_point_cloud_poisson_disk(): incompatible function arguments. The following argument types are supported:
    1. (v: numpy.ndarray, radius: float, target_num_samples: int = -1, random_seed: int = 0, sample_num_tolerance: float = 0.04) -> object

Invoked with: array([[-0.00224078,  0.16513148,  0.05084507],
       [-0.14718823,  0.1678087 , -0.0106656 ],
       [-0.11306737,  0.19896153,  0.19576581],
       ...,
       [-0.06319811,  0.15721506,  0.05869777],
       [ 0.07691269,  0.16609934, -0.04871012],
       [-0.2972071 ,  0.15462351,  0.07510553]], dtype=float32); kwargs: num_samples=56400
```
The error was resolved when I downgraded the point-cloud-utils version to `0.29.7` and below. More than delighted if it helps :)

**Comment by crazyMessi** [comment]
> At the time of the current issue submission, the point-cloud-utils version installed by default using pip is `0.30.0`. When running `run.py` and iterating until `step1_maxiter`, the following error occurs:：
> 
> ```
> Traceback (most recent call last):
>   File "run.py", line 272, in <module>
>     runner.train()
>   File "run.py", line 150, in train
>     idx = pcu.downsample_point_cloud_poisson_disk(gen_pointclouds, num_samples=int(self.conf.get_float('train.extra_points_rate')*point_gt.shape[0]))
> TypeError: downsample_point_cloud_poisson_disk(): incompatible function arguments. The following argument types are supported:
>     1. (v: numpy.ndarray, radius: float, target_num_samples: int = -1, random_seed: int = 0, sample_num_tolerance: float = 0.04) -> object
> 
> Invoked with: array([[-0.00224078,  0.16513148,  0.05084507],
>        [-0.14718823,  0.1678087 , -0.0106656 ],
>        [-0.11306737,  0.19896153,  0.19576581],
>        ...,
>        [-0.06319811,  0.15721506,  0.05869777],
>        [ 0.07691269,  0.16609934, -0.04871012],
>        [-0.2972071 ,  0.15462351,  0.07510553]], dtype=float32); kwargs: num_samples=56400
> ```
> 
> The error was resolved when I downgraded the point-cloud-utils version to `0.29.7` and below. More than delighted if it helps :)

太感谢了哥们 真的有用👍

**Comment by junshengzhou** [comment]
@Parallelopiped  Great thanks! :)

I have fixed the bug by adding the specific version for point-cloud-utils in the code instruction.
